import HL7 from "hl7-standard";

export function buildHL7Message(data: any): string {
  const mshSegment = [
    "MSH",
    "|",
    "^~\\&",
    "TTSH",
    "LabApp",
    "ReceiverApp",
    "ReceiverFac",
    new Date().toISOString().replace(/[-:]/g, "").slice(0, 14),
    "",
    "ORU^R01",
    "12345",
    "P",
    "2.5",
  ].join("|");

  const pidSegment = [
    "PID",
    "1",
    `${data.mrn}^^^Hosp^MR^ISO`,
    "",
    `${data.patient_name.split(" ")[1]}^${data.patient_name.split(" ")[0]}`,
    "",
    data.date_of_birth,
    data.sex,
  ].join("|");

  const obrSegment = [
    "OBR",
    "1",
    data.test_case_id,
    "",
    "GENETIC^Genetic Test",
    "",
    data.specimen_received,
  ].join("|");

  const obxSegments = [
    [
      "OBX",
      "1",
      "FT",
      "51969-4^Full narrative report^LN",
      "1",
      `Result: ${data.resultText}`,
      "",
      "",
      "",
      "",
      "F",
    ],
    [
      "OBX",
      "2",
      "CWE",
      "48018-6^Gene studied^LN",
      "1a",
      "CLN3^CLN3^HGNC",
      "",
      "",
      "",
      "",
      "F",
    ],
    [
      "OBX",
      "3",
      "CWE",
      "83005-9^Variant Category^LN",
      "2a",
      "LA26801-3^Simple^LN",
      "",
      "",
      "",
      "",
      "F",
    ],
    [
      "OBX",
      "4",
      "CWE",
      "48004-6^DNA change (HGVS)^LN",
      "2a",
      "c.1048delC^c.1048delC^HGVS.c",
      "",
      "",
      "",
      "",
      "F",
    ],
    [
      "OBX",
      "5",
      "CWE",
      "48005-3^Amino acid change (pHGVS)^LN",
      "2a",
      "p.Leu350CysfsX27^p.Leu350CysfsX27^HGVS.p",
      "",
      "",
      "",
      "",
      "F",
    ],
    [
      "OBX",
      "6",
      "CWE",
      "48002-0^Genomic Source Class^LN",
      "2a",
      "LA18197-6^Unknown Genomic Origin^LN",
      "",
      "",
      "",
      "",
      "F",
    ],
    [
      "OBX",
      "7",
      "CWE",
      "53037-8^Genetic variation clinical significance^LN",
      "2a",
      "LA6668-3^Pathogenic^LN",
      "",
      "",
      "",
      "",
      "F",
    ],
    [
      "OBX",
      "8",
      "CWE",
      "69548-6^Genetic variant assessment^LN",
      "2a",
      "LA9633-4^Present^LN",
      "",
      "",
      "",
      "",
      "F",
    ],
    [
      "OBX",
      "9",
      "ST",
      "47998-0^Variant display name^LN",
      "2a",
      "NM_001042432.2(CLN3):c.1048delC(p.Leu350CysfsX27)",
      "",
      "",
      "",
      "",
      "F",
    ],
  ].map((fields) => fields.join("|"));

  return [mshSegment, pidSegment, obrSegment, ...obxSegments].join("\r");
}
